version: "3.3"

networks:
  public:
    driver: bridge

services:
  jaeger-allinone:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    networks:
      public:
        aliases:
          - allinone
  
  service1:
    build: jaeger/
    image: spring_jaeger:latest
    ports:
      - "8080:8080"
    networks:
      public:
        aliases:
          - service1

  service2:
    build: jaeger/
    image: spring_jaeger:latest
    ports:
      - "8090:8080"
    networks:
      public:
        aliases:
          - service2