server.port: 8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: customer-service

  sleuth:
    # otel:
    #   exporter:
    #     otlp:
    #       endpoint: http://collector:6831
    jaeger:
      http-sender:
        url: http://localhost:14268/api/traces

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans