version: "3.5"

networks:
  public:
    driver: bridge

services:

  api-service:
    build: api-service/
    image: api-service:latest
    ports:
      - "8080:8080"
    networks:
      - public

  customer-service:
    build: ./customer-service/
    image: customer-service:latest
    ports:
      - "8081:8081"
    networks:
      - public

  # collector:
  #   image: logzio/otel-collector-traces
  #   environment:
  #     - LOGZIO_REGION=us
  #     - LOGZIO_TRACES_TOKEN=ZLLODwNFvNAeqpewaIwkZCUNuQhdVobU
  #   ports:
  #     - "1777:1777"
  #     - "9411:9411"
  #     - "9943:9943"
  #     - "6831:6831"
  #     - "6832:6832"
  #     - "14250:14250"
  #     - "14268:14268"
  #     - "4317:4317"
  #     - "55681:55681"
  #     - "8888:8888"

  jaeger-allinone:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "1777:1777"
      - "9411:9411"
      - "9943:9943"
      - "6832:6832"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "55681:55681"
      - "8888:8888"
    networks:
      public:
        aliases:
          - collector
